name: Continuous Check

on: [push]

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build with Gradle
        run: ./code/jvm/gradlew -p code/jvm check --info
